cc_library(
    name = "log",
    srcs = ["log.cc"],
    hdrs = ["log.h"],
    deps = [
        "@com_google_glog//:glog",
    ],
    visibility = [ "//visibility:public" ],
)

cc_library(
    name = "stats",
    srcs = [ "stats.cc" ],
    hdrs = [ "stats.h" ],
    visibility = [ "//visibility:public" ],
)

cc_library(
    name = "utilities",
    srcs = [ "utilities.cc" ],
    hdrs = [ "utilities.h" ],
    visibility = [ "//visibility:public" ],
)