
cc_library (
  name = "dimacs_parser",
  srcs = ["dimacs_cnf_parser.cc"],
  hdrs = ["dimacs_cnf_parser.h"],
  visibility = ["//visibility:public" ],
  deps = [
    "//src/clustersat/protocol:clustersat_proto",
    "@com_google_absl//absl/strings",
  ]
)